server:
  port:
    8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file://D:/Dev/workspaces-JAVA/intelliJ/DIO/dio-microservice-spring-cloud-config
          #uri: https://github.com/doflavio/dio-microservice-spring-cloud-config.git


